### ISSUE TITLE
Selected language not presisting in session

### ISSUE THREAD

**Issue by Abadulrehman** [EdJoPaTo/telegraf-i18n#12]
Hi, I was following along your example code to figure out how to let the user set their language in my bot. The problem is that the bot does not seem to be saving the locale for the session. For example, on doing
`ctx.i18n.locale('ru')`
the 'greeting' message does indeed have it's language changed. However, every subsequent message after that is still in the default language. I do have `useSession` set to true, and am also doing `bot.use(session())`. 

Am I missing something? Is there no way to make the language persist for the session?

**Comment by EdJoPaTo** [comment]
see https://github.com/telegraf/telegraf-i18n/issues/44
